networks:
  stock-dev-network:
    driver: bridge

version: "3"
services:
    stock:
        image: pythonstock/pythonstock:latest
        container_name: stock
        ports:
            - "8888:8888"
            - "9999:9999"
        volumes:
            - "../stock:/data/stock"
            - "./data/notebooks:/data/notebooks"
            - "./data/logs:/data/logs"
        environment:
            MYSQL_HOST: mysqlstock
            MYSQL_USER: root
            MYSQL_PWD: mysqlstock
            MYSQL_DB: stock_data
            MYSQL_PORT: 3306
            LANG: zh_CN.UTF-8
            LC_CTYPE: zh_CN.UTF-8
            PYTHONIOENCODING: utf-8
        links:
            - mysqlstock:mysqlstock
        restart: always
    mysqlstock:
        image: mysql:5.7
        container_name: mysqlstock
        ports:
            - "3306:3306"
        volumes:
            - "./data/mysqlstock/data:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: mysqlstock
            MYSQL_DATABASE: stock_data
            TZ: Asia/Shanghai
        command: [
            '--character-set-server=utf8mb4',
            '--collation-server=utf8mb4_general_ci',
            '--max_connections=3000'
        ]
        restart: always
        
